name: Node.js CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["build"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - name: Node install
        run: npm ci
      - name: Test
        run: npm test
      - name: show commit message
        run: echo "VITE_GIT_COMMIT=$(git log --format=reference -n 1 HEAD)" >> $GITHUB_ENV
      - name: Gem info
        run: npx -y tsx scripts/saveGemInfo.ts
      - name: Commit gem info
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.client_payload.commit_message }}
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
